### ISSUE TITLE
Detect collision between tanks and with castle 

### ISSUE THREAD

**Issue by valerandanne** [valerandanne/King-of-the-hill#12]
- [x] Create the bullet model 
- [x]  Implement the towers shooting
- [x]  Calculate the target of each bullet.
- [x] Detect if the bullet collided with its target.
- [x] Implement response to the collision.

**Comment by pgarralda-personal** [comment]
status?

**Comment by valerandanne** [comment]
- [X] Create the bullet model to charge the tank when created (10 bullets default)
