### ISSUE TITLE
Make the movement of the tanks to be in vectors. 

### ISSUE THREAD

**Issue by valerandanne** [valerandanne/King-of-the-hill#13]
Tanks shoud calculate the better path in order to reach their target and then move through the (x,y) axes in the most efficient way.

**Comment by pgarralda-personal** [comment]
Status?

**Comment by valerandanne** [comment]
[X] Fix the movement of the tank in order to make it more fluid and faster. 
[X] Fix the movement the tanks make when they reach their target
